
package fr.poec.formation.jee.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICalculatrice", targetNamespace = "http://ws.jee.formation.poec.aston.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICalculatrice {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addition", targetNamespace = "http://ws.jee.formation.poec.aston.fr/", className = "fr.poec.formation.jee.ws.Addition")
    @ResponseWrapper(localName = "additionResponse", targetNamespace = "http://ws.jee.formation.poec.aston.fr/", className = "fr.poec.formation.jee.ws.AdditionResponse")
    @Action(input = "http://ws.jee.formation.poec.aston.fr/ICalculatrice/additionRequest", output = "http://ws.jee.formation.poec.aston.fr/ICalculatrice/additionResponse")
    public double addition(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modulo", targetNamespace = "http://ws.jee.formation.poec.aston.fr/", className = "fr.poec.formation.jee.ws.Modulo")
    @ResponseWrapper(localName = "moduloResponse", targetNamespace = "http://ws.jee.formation.poec.aston.fr/", className = "fr.poec.formation.jee.ws.ModuloResponse")
    @Action(input = "http://ws.jee.formation.poec.aston.fr/ICalculatrice/moduloRequest", output = "http://ws.jee.formation.poec.aston.fr/ICalculatrice/moduloResponse")
    public int modulo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://ws.jee.formation.poec.aston.fr/", className = "fr.poec.formation.jee.ws.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://ws.jee.formation.poec.aston.fr/", className = "fr.poec.formation.jee.ws.DivisionResponse")
    @Action(input = "http://ws.jee.formation.poec.aston.fr/ICalculatrice/divisionRequest", output = "http://ws.jee.formation.poec.aston.fr/ICalculatrice/divisionResponse")
    public double division(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "soustration", targetNamespace = "http://ws.jee.formation.poec.aston.fr/", className = "fr.poec.formation.jee.ws.Soustration")
    @ResponseWrapper(localName = "soustrationResponse", targetNamespace = "http://ws.jee.formation.poec.aston.fr/", className = "fr.poec.formation.jee.ws.SoustrationResponse")
    @Action(input = "http://ws.jee.formation.poec.aston.fr/ICalculatrice/soustrationRequest", output = "http://ws.jee.formation.poec.aston.fr/ICalculatrice/soustrationResponse")
    public double soustration(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplication", targetNamespace = "http://ws.jee.formation.poec.aston.fr/", className = "fr.poec.formation.jee.ws.Multiplication")
    @ResponseWrapper(localName = "multiplicationResponse", targetNamespace = "http://ws.jee.formation.poec.aston.fr/", className = "fr.poec.formation.jee.ws.MultiplicationResponse")
    @Action(input = "http://ws.jee.formation.poec.aston.fr/ICalculatrice/multiplicationRequest", output = "http://ws.jee.formation.poec.aston.fr/ICalculatrice/multiplicationResponse")
    public double multiplication(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
